package com.auto.autoads.model.utils

data class Ad(
    var id: Long? = 1,
    var type: String? = "",
    var isApprove: Boolean = false,
    var category: String? = "",
    var marka: String? = "",
    var model: String? = "",
    var year: Int? = 0,
    var typeFuel: String? = "",
    var engineValue: Int? = 0,
    var price: Int? = 0,
    var registrationCountry: String?  = "",
    var transmission: String? = "",
    var distance: Int? = 0,
    var body: String? = "",
    var color: String? = "",
    var unit: String? = "",
    var wheel: String? = "",
    var doors: Int? = 0,
    var consist: String? = "",
    var safety: String? = "",
    var complectation: String? = "",
    var location: String? = "",
    var subscription: String? = "",
    var linkImages: MutableList<String>? = null, // 10 item?s
    var user: String? = "",
    var phone_1: String? = "",
    var phone_2: String? = "",
    var phone_3: String? = "",
    var phone_4: String? = "",
    var isNotFixedPrice: Boolean? = false,
    var diameter: Int? = 0,
    var width: Int? = 0,
    var height: Int? = 0,
    var places: Int = 0,
    var typeCargo: String? = "",
    var typeMoto: String? = "",
    var typeCoolingSystem: String? = "",
    var typeEngine: String? = "",
    var season: String? = "",
    var forCars: String? = ""
    ) {
    constructor() : this(
        0,
        "",
        false,
        "",
        "",
        "",
        0,
        "",
        0,
        0,
        "",
        "",
        0,
        "",
        "",
        "",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        mutableListOf()
        , "",
        "",
        "",
        "",
        "",
        false,
        0,
        0,
        0,
        0,
        "",
        "",
        ""
    )
}